name: Test, build and deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  endeleza:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    #- uses: actions/checkout@v3
    # - name: Copy .env
    #   run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    # - name: Install Dependencies
    #   run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    # - name: Generate key
    #   run: php artisan key:generate
    # - name: Directory Permissions
    #   run: chmod -R 777 storage bootstrap/cache
    # - name: SSH into server
    #   uses: charliex2/laravel-action@master
    #   with:
    #     host: ${{ secrets.SSH_IP_ADDRESS }}
    #     user: ${{ secrets.SERVER_USERNAME }}
    #     #password: ${{ secrets.SSH_USER_PASSWORD }}
    #     path: ${{ secrets.SSH_SERVER_PATH }}
    #     owner: www
    #     port: 22
    #   env:
    #     DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    # - uses: atymic/deployer-php-action@0.3.1
    #   with:
    #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
    #     # To disable host key checking (insecure!):
    #     ssh-disable-host-key-checking: true

    - name: SSH to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP_ADDRESS }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SSH_USER_PASSWORD }}
        #key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        debug: true
        script: |
          whoami
          ls -al
          cd /home/endeleza/endeleza
          git pull origin master

    # - name: Pull code from repository
    #   run: |
    #     cd /home/endeleza/endeleza
    #     git pull origin master
    