name: Test, build and deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  endeleza:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    - uses: actions/checkout@v3
    # - name: Copy .env
    #   run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: vendor
        key: composer-${{ hashFiles('composer.lock') }}

    - name: Run composer install
      run: composer install -n --prefer-dist
      env:
        APP_ENV: testing
    - name: Run tests
      run: ./vendor/bin/phpunit
      env:
        APP_ENV: testing
    - name: SSH to Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_IP_ADDRESS }}
        username: ${{ secrets.SSH_USERNAME }}
        #password: ${{ secrets.SSH_USER_PASSWORD }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        debug: true
        script: |
          whoami
          ls -al
          cd /home/capital/endeleza/
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          git pull origin master
    